### ISSUE TITLE
We need housekeeping scripts: utils

### ISSUE THREAD

**Issue by victorkane** [DurableDrupal/ddcmr#4]
### Overview

We need  `upsert-all.sh`, `remove-all.sh`, `backupdb`, and `restoredb` scripts.

We also need specifically parameterized scripts:

upsert {content-type} {<name> | all}

### Tasks

- [ ] On dev, do backupdb script
- [ ] On dev, do remove-all script
- [ ] On dev, do restoredb script
- [ ] Run remove-all script again
- [ ] On dev, do upsert-all script
- [ ] On dev, test
- [ ] On prod, pull, then do upsert-all script
- [ ] On prod, test with command line curl
